### PR TITLE
add Raise3D printer profiles

### PR DESCRIPTION
**Pull request by fr3ak2402**
**New printers:**

Raise3D Pro3:
Printer image (180x180)
Custom Printing Plate Model & Texture (PNG) - the manufacturer plate imitated
0.4 Nozzle Profile (Dual extruder)
0.4 Nozzle Profile (Left extruder)
0.4 Nozzle Profile (Right extruder)
0.10 Process Profile (Fine)
0.20 Process Profile (Standard)
0.25 Process Profile (Draft)

Raise3D Pro3 Plus:
Printer image (180x180)
Custom Printing Plate Model & Texture (PNG) - the manufacturer plate imitated
0.4 Nozzle Profile (Dual extruder)
0.4 Nozzle Profile (Left extruder)
0.4 Nozzle Profile (Right extruder)
0.10 Process Profile (Fine)
0.20 Process Profile (Standard)
0.25 Process Profile (Draft)

### CODE REVIEW

**Comment by fr3ak2402** [comment]
In addition, other Sovol profiles were completed

New printers:

Sovol SV06:
Printer image (180x180)
Custom Printing Plate Texture (PNG) - the manufacturer plate imitated
0.4 Nozzle Profile
0.18 Process Profile (Optimal)
0.20 Process Profile (Standard)

Sovol SV06 Plus:
Printer image (180x180)
Custom Printing Plate Texture (PNG) - the manufacturer plate imitated
0.4 Nozzle Profile
0.18 Process Profile (Optimal)
0.20 Process Profile (Standard)

**Comment by fr3ak2402** [comment]
Additionally, more Anycubic profiles were created and existing Anycubic profiles were extended

**Changes:**

Anycubic Viper:
0.15 Process Profile (Optimal)
0.30 Process Profile (Draft)

**New printers:**

Anycubic Chiron:
Printer image (180x180)
Custom Printing Plate Model & Texture (PNG) - the manufacturer plate imitated
0.4 Nozzle Profile
0.15 Process Profile (Optimal)
0.20 Process Profile (Standard)
0.30 Process Profile (Draft)

Anycubic Kobra Max:
Printer image (180x180)
Custom Printing Plate Model & Texture (PNG) - the manufacturer plate imitated
0.4 Nozzle Profile
0.15 Process Profile (Optimal)
0.20 Process Profile (Standard)
0.30 Process Profile (Draft)

**Review by SoftFever — APPROVED** [review]

**Comment by 2Elemental** [comment]
Can you also add profiles for Raise3D E2 please? Thanks in advance.

**Comment by fr3ak2402** [comment]
@2Elemental 
Yes, I have actually already created a profile for the Raised3D E2, which I will publish together with a big bunch of profiles (15 profiles).

This includes printers like the Raised3D Pro2 & Plus.

**Comment by 2Elemental** [comment]
Thank you so much. I sincerely hope Orca Slicer will be a good replacement for Ideamaker

**Comment by 2Elemental** [comment]
Any news on when we can expect these profiles?

**Comment by webwings74** [comment]
Can the older Raise3D Pro2/Pro2 Plus (HyperSpeed) be added? I'm unsuccesfull in using Orca Slicer 2.3.2 at the moment for this printer.

**Comment by Landona24** [comment]
Love community contributions, turns out the code I put together and shared so I could run Prusaslicer instead of IdeaMaker ended up in the profile I'm trying out in Orcaslicer. :smiley:

If there's any interest in the source of the Pro3 profile: https://www.reddit.com/r/Raise3d/comments/xjeghm/how_to_using_prusaslicer_with_your_raise3d_pro3/

**Pull request merged**
